### ISSUE TITLE
main grid width 90 rem 고정 시 생기는 이슈

### ISSUE THREAD

**Issue by healtheloper** [healtheloper/airbnb#19]
<img width="1334" alt="스크린샷 2022-05-26 오후 5 35 57" src="https://user-images.githubusercontent.com/58503584/170451432-ccbc2d2a-8424-4203-a981-c88654e870cc.png">

width 를 90rem 으로 고정해서, 사용자의 화면이 90rem 보다 작아졌을 때 스크롤이 생기고 위와같이 밀리는 현상이 생깁니다~!
header 에서도 비슷한 로직을 90rem 고정한 것을 지우고 작업진행중었는데요, 해당 고정값을 지우는게 맞을까요?

```jsx
export default function MainPage() {
  return (
    <>
      <Background />
      <Box sx={{ width: '90rem', margin: '0 auto', padding: '5rem' }}>
```

**Comment by muffin9** [comment]
지금 저도 잠깐 확인해봤는데 저렇게 잡은 이유가 아마
저는 Header 부분이랑 MainPage 영역을 피그마 시안에 1440px로 잡혀있어서 width값을 고정시켰어요(반응형은 생각 안했네요ㅎㅎ...),
width대신 maxWidth를 90rem으로 주면 브라우저 크기가 줄어들때 스크롤이 생기지 생기지 않고 동작되는거 같아요!

**Comment by healtheloper** [comment]
넵 그럼 다음 PR 에 포함시키면 좋을 것 같아요!!
