### ISSUE TITLE
footer key props 에러 임시 처리

### ISSUE THREAD

**Issue by muffin9** [healtheloper/airbnb#21]
<img width="685" alt="key props 해결" src="https://user-images.githubusercontent.com/45479309/170619266-f624453b-7a86-44d4-ab25-42cec05d796a.png">

현재 브라우저 창에서 반복되는 엘리먼트 들에 대하여 key props를 전달해주지 않아 생겨나는 문제인데, 해당 사항 우선 uuid 대신 쓸만한 고유 값으로 임시 수정하도록 할게요!

**Comment by healtheloper** [comment]
#22 👍
