### ISSUE TITLE
체크인/체크아웃 입력 후 삭제시 요금 데이터 초기화 안됨

### ISSUE THREAD

**Issue by healtheloper** [healtheloper/airbnb#73]
<img width="976" alt="스크린샷 2022-06-09 오후 5 27 46" src="https://user-images.githubusercontent.com/58503584/172801519-2b5ce2c8-7a38-48e0-a4db-9cb4eadbcb46.png">

- PriceDispatch 넣어서 해결할 수 있을 것 같아요

**Comment by muffin9** [comment]
Slider 에러 관련 처리하고 있어서 이것도 한꺼번에 같이 할게요~
